version: '3'

services:  
  ml-challange:
    image: ml-challange:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8480:8080"
      - "443:8080"
      - "8080:8080"
    volumes:
      - proyect_data:/data
    restart: unless-stopped    
    depends_on: 
      - redis # This service depends on redis. Start that first.   
    environment: # Pass environment variables to the service
      REDIS_URL: redis:6379     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    volumes:
      - redis_data:/data

  # Redis Service   
  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service    
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  proyect_data:
    driver: local
  redis_data:
    driver: local